services:
  # Service Proxy
  - type: web
    name: solo-proxy
    env: node
    plan: free
    buildCommand: cd proxy && npm install
    startCommand: cd proxy && npm start
    envVars:
      - key: NODE_ENV
        value: test
      - key: POS_PROVIDER
        value: lacaisse
      - key: LACAISSE_BASE_URL
        value: https://api-legacy.lacaisse.ma
      - key: LACAISSE_LOGIN
        sync: false
      - key: LACAISSE_PASSWORD
        sync: false
      - key: LACAISSE_API_TOKEN
        sync: false
      - key: LACAISSE_CAISSE_ID
        value: "4418"
      - key: LACAISSE_ID_CAISSE_LIST
        value: "4418"
      - key: LACAISSE_JOURNAL_ID
        value: "3"
      - key: FRONTEND_URL
        fromService:
          type: static
          name: solo-pro-frontend
          property: host

  # Service Frontend
  - type: static
    name: solo-pro-frontend
    buildCommand: echo "No build needed for static site"
    staticPublishPath: .

